---
- hosts: "{{ target }}"
  pre_tasks:
    - apt:
        name: libffi-dev
        update_cache: yes
      sudo: true

    - name: Get a newer git
      apt:
        name: git
        default_release: wheezy-backports
        state: latest
      sudo: true

  roles:
    - role: common
      sudo: true

    - role: forge_ssl
      sudo: true

    - role: redmine
      ruby_builder_ruby_version: '2.1.5'
      redmine_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge/redmine.git
      redmine_version: forge
      redmine_dir: /opt/redmine
      redmine_db_name: "{{ db_name }}"
      redmine_db_host: "{{ db_host }}"
      redmine_db_user: "{{ db_user }}"
      redmine_db_pass: "{{ db_pass }}"
      ssl_cert_location: "{{ forge_ssl_cert_wholechain }}"
      ssl_key_location: "{{ forge_ssl_key }}"
      sudo: true
      tags: core

    - role: redmine_my_page_queries
      redmine_dir: /opt/redmine
      plugin_name: redmine_my_page_queries
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_my_page_queries.git
      sudo: true
      tags:
        - plugin
        - my_page_queries

    - role: redmine_backlogs
      redmine_dir: /opt/redmine
      plugin_name: redmine_backlogs
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_backlogs.git
      sudo: true
      tags:
        - plugin
        - backlogs

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_pdf_macro
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_pdf_macro.git
      sudo: true
      tags:
        - plugin
        - pdf_macro

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_statistics
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_statistics.git
      sudo: true
      tags:
        - plugin
        - statistics

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_cas
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_cas.git
      sudo: true
      tags:
        - plugin
        - cas

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_ldap_sync
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_ldap_sync.git
      sudo: true
      tags:
        - plugin
        - ldap_sync

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_wiki_extensions
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_wiki_extensions.git
      plugin_version: forge
      sudo: true
      tags:
        - plugin
        - wiki_extensions

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_email_notification_content_filter
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_email_notification_content_filter.git
      sudo: true
      tags:
        - plugin
        - email_notification_content_filter

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_anonymous_watchers
      plugin_version: forge
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_anonymous_watchers.git
      sudo: true
      tags:
        - plugin
        - anonymous_watchers

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_impasse
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_impasse.git
      sudo: true
      tags:
        - plugin
        - impasse

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_canned_responses
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_canned_responses.git
      sudo: true
      tags:
        - plugin
        - canned_responses

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_extended_watchers
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_extended_watchers.git
      sudo: true
      tags:
        - plugin
        - extended_watchers

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_watcher_groups
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge-redmine-plugins/redmine_watcher_groups.git
      sudo: true
      tags:
        - plugin
        - watcher_groups

    - role: forge_error_pages
      target_webserver: nginx
      sudo: true
      tags:
        - error_pages

    - role: openfire
      new_install: false
      sudo: true
      tags: xmpp

  post_tasks:
    - name: link the custom error pages on nginx
      sudo: true
      replace:
        dest: /etc/nginx/sites-available/redmine
        regexp: ^(\s+)error_page 502.*
        replace: \1location /errors/ {\n\1\1root  /var/www/errors;\n\1\1internal;\n\1}
        backup: yes

    - name: Set cron job to receive email
      sudo: true
      cron:
        name: Get email from GMail
        minute: '*/5'
        user: redmine
        job: cd /var/www/redmine/redmine-2.2.4 && rake -f /var/www/redmine/redmine-2.2.4/Rakefile redmine:email:receive_imap RAILS_ENV="production"  host=imap.gmail.com username=support@forgeservicelab.fi ssl=yes port=993 password=Tummapall0h project=forge-support tracker=Support allow_override=tracker,project,priority,assigned_to

    - name: Set cron job to synchronize LDAP
      sudo: true
      cron:
        name: Syncrhonize LDAP users and groups
        minute: '*/10'
        user: redmine
        job: cd /var/www/redmine/redmine-2.2.4 && RAILS_ENV=production rake redmine:plugins:ldap_sync:sync_all
