---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - include: pre_play.yml

- hosts: "{{ target_group }}"
  pre_tasks:
    - apt:
        name: libffi-dev
        update_cache: yes
      sudo: true

    - name: Get a newer git
      apt:
        name: git
        default_release: wheezy-backports
        state: latest
      sudo: true

  roles:
    - role: common
      web_domain: support-devel.forgeservicelab.fi
      sudo: true

    - role: forge_ssl
      sudo: true

    - role: redmine
      ruby_builder_ruby_version: '2.2.1'
      redmine_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge/redmine.git
      redmine_version: tag-3.0.1-branchoff
      redmine_dir: /opt/redmine
      redmine_db_name: redmine_development
      redmine_db_host: dbserver.forgeservicelab.fi
      redmine_db_user: redmine
      redmine_db_pass: voTSC7bsKARFJEG
      ssl_cert_location: "{{ forge_ssl_cert_wholechain }}"
      ssl_key_location: "{{ forge_ssl_key }}"
      sudo: true

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_cas
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge_new-redmine-plugins/redmine_cas.git
      sudo: true

    - role: generic_install
      redmine_dir: /opt/redmine
      plugin_name: redmine_ldap_sync
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge_new-redmine-plugins/redmine_ldap_sync.git
      sudo: true

    - role: redmine_backlogs
      redmine_dir: /opt/redmine
      plugin_repo: ssh://gitlab@git.forgeservicelab.fi:10022/forge_new-redmine-plugins/redmine_backlogs.git
      sudo: true

  post_tasks:
    - name: Set cron job to receive email
      sudo: true
      cron:
        name: Get email from GMail
        minute: '*/5'
        user: redmine
        job: cd /var/www/redmine/redmine-2.2.4 && rake -f /var/www/redmine/redmine-2.2.4/Rakefile redmine:email:receive_imap RAILS_ENV="production"  host=imap.gmail.com username=support@forgeservicelab.fi ssl=yes port=993 password=Tummapall0h project=forge-support tracker=Support allow_override=tracker,project,priority,assigned_to

    - name: Set cron job to synchronize LDAP
      sudo: true
      cron:
        name: Syncrhonize LDAP users and groups
        minute: '*/10'
        user: redmine
        job: cd /var/www/redmine/redmine-2.2.4 && RAILS_ENV=production rake redmine:plugins:ldap_sync:sync_all
