---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - include: pre_play.yml

- hosts: "{{ target_group }}"
  roles:
    - role: common
      web_domain: support-devel.forgeservicelab.fi
      sudo: true

    - role: redmine
      ruby_builder_ruby_version: '1.9.3-p547'
      redmine_dir: /opt/redmine
      redmine_db_name: redmine_development
      redmine_db_host: dbserver.forgeservicelab.fi
      redmine_db_user: redmine
      redmine_db_pass: voTSC7bsKARFJEG
      sudo: true
